---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress
  namespace: flux-system
spec:
  interval: 2m
  dependsOn:
    - name: linkerd
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./ingress"
  prune: true
  timeout: 5m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: ingress-nginx
      namespace: ingress
  postBuild:
    substitute:
      ingress_nginx_version: "~4"
