---
apiVersion: v1
kind: Secret
metadata:
  name: linkerd-proxy-injector-k8s-tls
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: proxy-injector
    linkerd.io/control-plane-ns: linkerd
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI5RENDQVpxZ0F3SUJBZ0lRRHV6bm4yRkhQSHdmd2Z4MmViQlhzekFLQmdncWhrak9QUVFEQWpBbE1TTXcKSVFZRFZRUURFeHB5YjI5MExteHBibXRsY21RdVkyeDFjM1JsY2k1c2IyTmhiREFnRncweU16RXdNall3T0RJMgpNRGhhR0E4eU1EY3pNVEF4TXpBNE1qWXdPRm93TFRFck1Da0dBMVVFQXhNaWJHbHVhMlZ5WkMxd2NtOTRlUzFwCmJtcGxZM1J2Y2k1c2FXNXJaWEprTG5OMll6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJIWkQKVUI5YS9TR3I1NlJpdm5ZZWxIRjVWc1ZaeCtFMTZZVngwSkZHSTFZVlhaV0xFYWh5RXc4aksxR3FZTGh0S2xCaQpBdnVna0ZOV2hCZjNWL3gzMkFlamdhRXdnWjR3RGdZRFZSMFBBUUgvQkFRREFnZUFNQjBHQTFVZEpRUVdNQlFHCkNDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQWRCZ05WSFE0RUZnUVVBUHQxN0h0VVMyOExXamNRNXN3TE5OeE8KNGZzd0h3WURWUjBqQkJnd0ZvQVVsQnJJL1hLWHo4b0RVSFZRU1BZNklhbHJyRGN3TFFZRFZSMFJCQ1l3SklJaQpiR2x1YTJWeVpDMXdjbTk0ZVMxcGJtcGxZM1J2Y2k1c2FXNXJaWEprTG5OMll6QUtCZ2dxaGtqT1BRUURBZ05JCkFEQkZBaUJFS3p4U0lER3BNMTAzNGN6UEs5WUx5N3gxdklzbm54NVFGaVF6amRLUlNRSWhBT29nMCtacTRIaXoKOUJoTWdiL3U1endXQm9JWWd2a09TV2wxaWdBaDZva0wKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUhBbUhZQzFEaExBOXVhNmhidG02UUNKMXBnOGY5M1A2UzV3YnlkWXVCSmVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFZGtOUUgxcjlJYXZucEdLK2RoNlVjWGxXeFZuSDRUWHBoWEhRa1VZalZoVmRsWXNScUhJVApEeU1yVWFwZ3VHMHFVR0lDKzZDUVUxYUVGL2RYL0hmWUJ3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
