---
apiVersion: v1
kind: Secret
metadata:
  name: linkerd-sp-validator-k8s-tls
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: destination
    linkerd.io/control-plane-ns: linkerd
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI4akNDQVplZ0F3SUJBZ0lSQUxMUWF4T1NkWS9QZFIvdDJHNDMxbEF3Q2dZSUtvWkl6ajBFQXdJd0pURWoKTUNFR0ExVUVBeE1hY205dmRDNXNhVzVyWlhKa0xtTnNkWE4wWlhJdWJHOWpZV3d3SUJjTk1qTXhNREkyTURnegpOak14V2hnUE1qQTNNekV3TVRNd09ETTJNekZhTUNzeEtUQW5CZ05WQkFNVElHeHBibXRsY21RdGMzQXRkbUZzCmFXUmhkRzl5TG14cGJtdGxjbVF1YzNaak1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRU9qZUIKaUQxMEpVUlNRL0o0WmNFSDlEd1RobUpweDYzeTY4K2pXTWpWSm52MUp3WDZkL1VoR0VWRGtvMXZmTCtkTDd4aAp6SHoxZVQxRlF1Mk1CS1ZuektPQm56Q0JuREFPQmdOVkhROEJBZjhFQkFNQ0I0QXdIUVlEVlIwbEJCWXdGQVlJCkt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01CMEdBMVVkRGdRV0JCUS9FdTd0ekVVYTZ3bWl4dzZBL0tFR3J6dDAKU0RBZkJnTlZIU01FR0RBV2dCU1VHc2o5Y3BmUHlnTlFkVkJJOWpvaHFXdXNOekFyQmdOVkhSRUVKREFpZ2lCcwphVzVyWlhKa0xYTndMWFpoYkdsa1lYUnZjaTVzYVc1clpYSmtMbk4yWXpBS0JnZ3Foa2pPUFFRREFnTkpBREJHCkFpRUF3cWF0WWFMTzlCT3VnLzhWNEhSZ2Zndko5UExoVTVlNjB6RVFhVWFkWXZzQ0lRRFRBc0pybElOMUpQc3QKa2pkMDA5NnpORitDbWM3ZFh6MHBnYmF4SG9DMi9nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUd0TGkxVHd2Zm9mbXdteHZ3YXlrdCtqb2J5Ylh3M3VZRVZKMFNGZTF5dDdvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFT2plQmlEMTBKVVJTUS9KNFpjRUg5RHdUaG1KcHg2M3k2OCtqV01qVkpudjFKd1g2ZC9VaApHRVZEa28xdmZMK2RMN3hoekh6MWVUMUZRdTJNQktWbnpBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
