---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-tracing
  namespace: linkerd
spec:
  interval: 30m
  dependsOn:
    - name: linkerd-control-plane
  chart:
    spec:
      chart: linkerd-jaeger
      version: "~30"
      sourceRef:
        kind: HelmRepository
        name: linkerd-charts
        namespace: linkerd
  values:
    jaeger:
      enabled: false
    collector:
      config:
        exporters:
          jaeger:
            endpoint: tempo.monitoring:14250
