---
apiVersion: v1
kind: Secret
metadata:
  name: linkerd-policy-validator-k8s-tls
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: destination
    linkerd.io/control-plane-ns: linkerd
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI5ekNDQVo2Z0F3SUJBZ0lRSmt5cWlRU244WUQxVzBCaG1sZWhWREFLQmdncWhrak9QUVFEQWpBbE1TTXcKSVFZRFZRUURFeHB5YjI5MExteHBibXRsY21RdVkyeDFjM1JsY2k1c2IyTmhiREFnRncweU16RXdNall3T0RNeQpNelphR0E4eU1EY3pNVEF4TXpBNE16SXpObG93THpFdE1Dc0dBMVVFQXhNa2JHbHVhMlZ5WkMxd2IyeHBZM2t0CmRtRnNhV1JoZEc5eUxteHBibXRsY21RdWMzWmpNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUUKYjZ4ZThLZklCUmtnRVRpK2JFeUQ4SDlzWFJQdnVLTnlaMUhOOWhQZ01mbFVMcmdiWEt6L2RqWTFhSW94ekl1NwpBWXkwalZlTFNlZE5KQlJaVHpmSWthT0JvekNCb0RBT0JnTlZIUThCQWY4RUJBTUNCNEF3SFFZRFZSMGxCQll3CkZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQjBHQTFVZERnUVdCQlNwQURUT3FiZXFnTHIyOFV3SzZmVE8KWUZoN29UQWZCZ05WSFNNRUdEQVdnQlNVR3NqOWNwZlB5Z05RZFZCSTlqb2hxV3VzTnpBdkJnTlZIUkVFS0RBbQpnaVJzYVc1clpYSmtMWEJ2YkdsamVTMTJZV3hwWkdGMGIzSXViR2x1YTJWeVpDNXpkbU13Q2dZSUtvWkl6ajBFCkF3SURSd0F3UkFJZ1JCd1ZCTGN0b0JoVktDQnRrQmlCdGpFejhTZjc1aXJ2UTVLMkxmNWlycWtDSUdhcXlEZ28Kd1FRT1BYRVlHeHBiWjF0SXpkcDBhV2pud1pEQytMU0ZEWWhvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUpmSDd5WE9vSXlZY0MzSGtmNHZpTjNhWFJRMURtaXhyWEhJdklpeHhiSU9vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFYjZ4ZThLZklCUmtnRVRpK2JFeUQ4SDlzWFJQdnVLTnlaMUhOOWhQZ01mbFVMcmdiWEt6LwpkalkxYUlveHpJdTdBWXkwalZlTFNlZE5KQlJaVHpmSWtRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
