---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  interval: 30m
  dependsOn:
    - name: linkerd-crds
  chart:
    spec:
      chart: linkerd-control-plane
      version: "~1"
      sourceRef:
        kind: HelmRepository
        name: linkerd-charts
        namespace: linkerd
  values:
    identity:
      # use CA certs from given configmap
      externalCA: true
      # causes the chart to skip the certificate secret creation, as we created the identity-issuer certificate secret beforehand
      issuer:
        scheme: kubernetes.io/tls
    proxyInjector:
      externalSecret: true
      caBundle: |
        -----BEGIN CERTIFICATE-----
        MIIBjzCCATWgAwIBAgIQYbslgDE1AV3JMXZwQ327NzAKBggqhkjOPQQDAjAlMSMw
        IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAgFw0yMzEwMjYwNzM3
        MDZaGA8yMDczMTAxMzA3MzcwNlowJTEjMCEGA1UEAxMacm9vdC5saW5rZXJkLmNs
        dXN0ZXIubG9jYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARK5duHxVK9RyRQ
        v4O3DJzLFEp9uQ9Ye+kCmrQmWUyyLzyeB/bYKKaQpBslnevp5hAFOy05y0+uxpkC
        //37Fn+co0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
        BgNVHQ4EFgQUlBrI/XKXz8oDUHVQSPY6IalrrDcwCgYIKoZIzj0EAwIDSAAwRQIh
        AKx6BJtpNjvnf+glC1wIUprnUMV7lVG54sVqclVSiDUUAiBVie2ITFRyYiwPzk+1
        wkih3wGo5fSbbwxxWNOwWYoM5Q==
        -----END CERTIFICATE-----
    profileValidator:
      externalSecret: true
      caBundle: |
        -----BEGIN CERTIFICATE-----
        MIIBjzCCATWgAwIBAgIQYbslgDE1AV3JMXZwQ327NzAKBggqhkjOPQQDAjAlMSMw
        IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAgFw0yMzEwMjYwNzM3
        MDZaGA8yMDczMTAxMzA3MzcwNlowJTEjMCEGA1UEAxMacm9vdC5saW5rZXJkLmNs
        dXN0ZXIubG9jYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARK5duHxVK9RyRQ
        v4O3DJzLFEp9uQ9Ye+kCmrQmWUyyLzyeB/bYKKaQpBslnevp5hAFOy05y0+uxpkC
        //37Fn+co0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
        BgNVHQ4EFgQUlBrI/XKXz8oDUHVQSPY6IalrrDcwCgYIKoZIzj0EAwIDSAAwRQIh
        AKx6BJtpNjvnf+glC1wIUprnUMV7lVG54sVqclVSiDUUAiBVie2ITFRyYiwPzk+1
        wkih3wGo5fSbbwxxWNOwWYoM5Q==
        -----END CERTIFICATE-----
    policyValidator:
      externalSecret: true
      caBundle: |
        -----BEGIN CERTIFICATE-----
        MIIBjzCCATWgAwIBAgIQYbslgDE1AV3JMXZwQ327NzAKBggqhkjOPQQDAjAlMSMw
        IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAgFw0yMzEwMjYwNzM3
        MDZaGA8yMDczMTAxMzA3MzcwNlowJTEjMCEGA1UEAxMacm9vdC5saW5rZXJkLmNs
        dXN0ZXIubG9jYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARK5duHxVK9RyRQ
        v4O3DJzLFEp9uQ9Ye+kCmrQmWUyyLzyeB/bYKKaQpBslnevp5hAFOy05y0+uxpkC
        //37Fn+co0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
        BgNVHQ4EFgQUlBrI/XKXz8oDUHVQSPY6IalrrDcwCgYIKoZIzj0EAwIDSAAwRQIh
        AKx6BJtpNjvnf+glC1wIUprnUMV7lVG54sVqclVSiDUUAiBVie2ITFRyYiwPzk+1
        wkih3wGo5fSbbwxxWNOwWYoM5Q==
        -----END CERTIFICATE-----
    podMonitor:
      enabled: true
