---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-smi
  namespace: linkerd
spec:
  interval: 30m
  dependsOn:
    - name: linkerd-crds
  chart:
    spec:
      chart: linkerd-smi
      version: "~1"
      sourceRef:
        kind: HelmRepository
        name: linkerd-smi-charts
        namespace: linkerd
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
