---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: linkerd
spec:
  interval: 30m
  chart:
    spec:
      chart: linkerd-crds
      version: "~1"
      sourceRef:
        kind: HelmRepository
        name: linkerd-charts
        namespace: linkerd
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
