---
kind: Secret
apiVersion: v1
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: identity
    linkerd.io/control-plane-ns: linkerd
data:
  cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJzakNDQVZxZ0F3SUJBZ0lRZFBNRHdjRVBBTTBiVnZXME9VT3F4ekFLQmdncWhrak9QUVFEQWpBbE1TTXcKSVFZRFZRUURFeHB5YjI5MExteHBibXRsY21RdVkyeDFjM1JsY2k1c2IyTmhiREFnRncweU16RXdNall3TnpRdwpNemhhR0E4eU1EY3pNVEF4TXpBM05EQXpPRm93S1RFbk1DVUdBMVVFQXhNZWFXUmxiblJwZEhrdWJHbHVhMlZ5ClpDNWpiSFZ6ZEdWeUxteHZZMkZzTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFcm4ybDc4MUEKY0Z1ckhsdDFaOUI5SjFOTWtzakEyYzQ1dXpXVmxTZ1lQSkJKQU5OM0hVK1dqUGo2UFJVR3lxRXJKMDNoSU15RQpQMXgwRFZLRGl4ZmQzYU5tTUdRd0RnWURWUjBQQVFIL0JBUURBZ0VHTUJJR0ExVWRFd0VCL3dRSU1BWUJBZjhDCkFRQXdIUVlEVlIwT0JCWUVGS2FLT3VMZTJwUVZ6blNsWUt3UEEzWGwySVQvTUI4R0ExVWRJd1FZTUJhQUZKUWEKeVAxeWw4L0tBMUIxVUVqMk9pR3BhNnczTUFvR0NDcUdTTTQ5QkFNQ0EwWUFNRU1DSHlrek80ckhGNHRGT09mYwpDZGt1RHRYcHZHVVp4dTQybEJyOXljRnNlcVFDSURJTEI2YmR2ejlsd3BzMWZZc2lQYjhHSmFHVkxpWWNCU1pZCm5sdVNGelROCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  key.pem: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUYyQXhwRktkajN2MzdwZ2I5Sm00aHhsdjNmY2xyS2wwOC9WRTI4c2ZzWE5vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFcm4ybDc4MUFjRnVySGx0MVo5QjlKMU5Na3NqQTJjNDV1eldWbFNnWVBKQkpBTk4zSFUrVwpqUGo2UFJVR3lxRXJKMDNoSU15RVAxeDBEVktEaXhmZDNRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
