---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: examiner
  namespace: apps
spec:
  chart:
    spec:
      chart: application
      version: "~1"
      sourceRef:
        kind: HelmRepository
        name: chart-repo
        namespace: apps
      interval: 60m
  interval: 30s
  values:
    image:
      repository: quay.io/heubeck/examiner
      tag: 1.11.19
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi
    container:
      port: 8080
    livenessProbe:
      path: /.well-known/live
    readinessProbe:
      path: /.well-known/ready
    configuration:
      ECHO_VALUE: 👋 Welcome to the kind side
    monitoring:
      serviceMonitor: true
      metricsPath: /metrics
    linkerd:
      enabled: true
    canary:
      enabled: true
      interval: 30s
      stepWeight: 10
      threshold: 2
      metrics:
        - name: request-success-rate
          # minimum req success rate (non 5xx responses)
          # percentage (0-100)
          thresholdRange:
            min: 99
          interval: 30s
        - name: request-duration
          # maximum req duration P99
          # milliseconds
          thresholdRange:
            max: 500
          interval: 30s
